name: OWASP Dependency Check
on:
  push:
    branches:
      - master
jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
        
      - name: Install dependencies
        run: npm install  
        
      - name: Run OWASP Dependency Check
        run: |
          docker run --rm \
            -v $(pwd):/src \
            -v $(pwd)/odc-data:/usr/share/dependency-check/data \
            -v $(pwd)/report:/report \
            owasp/dependency-check:latest \
            --project "owasp-test" 
            --scan /src 
            --format HTML 
            --out /report 
            --nvdApiKey ${{ secrets.NVD_API_KEY }}
        
      - name: Upload OWASP Dependency Check report
        with:
          name: dependency-check-report
          path: report
