name: OWASP Dependency Check
"on":
  push:
    branches:
      - master
jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: adopt
          java-version: "11"
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
      - name: Run OWASP Dependency Check
        uses: "docker://owasp/dependency-check:latest"
        with:
          args: |
            --scan /github/workspace
            --format HTML
            --project "My Project"
            --out /github/workspace/report
      - name: Upload OWASP Dependency Check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: report
