name: OWASP Dependency Check
"on":
  push:
    branches:
      - master
jobs:
  owasp-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: "11"
      - name: Run OWASP Dependency Check
        uses: "docker://owasp/dependency-check:latest"
        with:
          args: |
            --scan /github/workspace
            --format HTML
            --project "My Project"
            --out /github/workspace/report
      - name: Upload OWASP Dependency Check report
        uses: actions/upload-artifact@v2
        with:
          name: dependency-check-report
          path: report
